In [ ]:
#create 2D array
import numpy as np
num_array=np.array([[1,3,5,7],[2,4,6,8]])
print('Original array:\n',num_array)

#flatten the array into 10
print('Flattened array:\n',np.ndarray.flatten(num_array))

Original array:
 [[1 3 5 7]
 [2 4 6 8]]
Flattened array:
 [1 3 5 7 2 4 6 8]


In [ ]:
#iteration through one dimenson array
#create an array of books
books=np.array(["Data Science with python","Machines are Learning","DIY-Deep Learning"])
#print the dimension of the array
print("The array 'books' is",books.ndim,"dimensional array\n")
#print each element of the array
for i in books:
  print(i)

The array 'books' is 1 dimensional array

Data Science with python
Machines are Learning
DIY-Deep Learning


In [ ]:
#iteration through 2D array
#create an array of books
books=np.array([["Data science with python","Machines are Learning","DIY-Deep Learning"]])
#print the dimension of the array
print("The array 'books' is",books.ndim,"dimensional array\n")
#print each element of the array
for i in books:
  print(i)

The array 'books' is 2 dimensional array

['Data science with python' 'Machines are Learning' 'DIY-Deep Learning']


In [ ]:
#iteration through 2D array #to print a value in one by one order
#create an array of books
books=np.array([["Data science with python","Machines are Learning","DIY-Deep Learning"],[25,55.5,40]])
#print the dimension of the array
print("The array 'books' is",books.ndim,"dimensional array\n")
#print each element of the array
for i in books:
  for j in i:
     print(j)

The array 'books' is 2 dimensional array

Data science with python
Machines are Learning
DIY-Deep Learning
25
55.5
40


In [ ]:
#create a array
import numpy as np
num_array1 numpy. arange(size)
num_array2 numpy.arange (size)
# NumPy array
initialTime time.time()
resultant_array num_array1 num_array2
# calculate execution time
print("Time taken by arrays:",
    (time.time() initialTime), 
    "seconds")

SyntaxError: ignored

In [ ]:
import numpy as np  #program to identify the average of temp in am,pm and day wise example1
import time
a=np.array([28,28,28,29,28,29,29])
b=np.array([36,36,36,36,37,37,37])
print("Temp at 9am:\n",a)
print("Temp at 6pm:\n",a)
init_time=time.time()
print("Mean temp at 9 am:",np.mean(a))
print("Mean temp at 6pm:",np.mean(b))
print("Mean temp of day 1-7:",(a+b)/2)
#Calculate execution time
print("Time taken by lists :",(time.time()-init_time),"Seconds")

Temp at 9am:
 [28 28 28 29 28 29 29]
Temp at 6pm:
 [28 28 28 29 28 29 29]
Mean temp at 9 am: 28.428571428571427
Mean temp at 6pm: 36.42857142857143
Mean temp of day 1-7: [32.  32.  32.  32.5 32.5 33.  33. ]
Time taken by lists : 0.002386808395385742 Seconds


In [ ]:
import numpy as np #program to identify the average of temp in am,pm and day wise example2
a=np.array([[32,32,32,31,31,31,31],[36,36,36,36,36,36,35]])
init_time=time.time() #Calculate time at that moment
print("Actual Array:\n",a)
print("Mean temp at 9 am and 6pm",np.mean(a,1))
print("Mean temp of day 1-7",np.mean(a,0))
#Calculate execution time
print("Time taken by Array :",(time.time()-init_time),"Seconds") #aftr calc time - that init tym stored

Actual Array:
 [[32 32 32 31 31 31 31]
 [36 36 36 36 36 36 35]]
Mean temp at 9 am and 6pm [31.42857143 35.85714286]
Mean temp of day 1-7 [34.  34.  34.  33.5 33.5 33.5 33. ]
Time taken by Array : 0.0029277801513671875 Seconds


In [ ]:
#add 2 usng function
def addition(num1,num2):
  add=num1+num2
  return(add)


In [ ]:
#import reduce function from the functools library
from functools import reduce
num_list=[1,2,3,4,5,6,7,8,9,10]
#the following function prints factorial of 5
reduce(lambda a,b: a*b,num_list)

3628800

In [ ]:
#determining the minimum of a numeric tuple using reduce
from functools import reduce #import reduce function from the functools library
num_tup=(0,-8,55,-100,1000,33) #create a numeric tuple
reduce(lambda x,y: x if (x<y) else y, num_tup) #the following function prints the maximum value from the iterable passed

In [ ]:
import numpy as np
array_example=np.array([[[0,1,2,3],
                         [4,5,6,7]],
                         [[0,1,2,3],
                         [4,5,6,7]],
                         [[0,1,2,3],
                         [5,5,6,7]]])
print(array_example)


[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [5 5 6 7]]]


In [ ]:
import numpy as np
array_example=np.array([[[0,1],[4,5]],[[0,1],[4,5]],[[0,1],[4,5]]])
print(array_example)

[[[0 1]
  [4 5]]

 [[0 1]
  [4 5]]

 [[0 1]
  [4 5]]]


In [ ]:
import numpy as np
a=np.array([[[0,1],[4,5]],[[2,4],[6,8]],[[3,5],[2,1]]])
print("the Mean is:",np.mean(a,1))


the Mean is: [[2.  3. ]
 [4.  6. ]
 [2.5 3. ]]


In [ ]:
print('size:',array_example.size)
print('Dimension:',array_example.ndim)
#print(array_example)
print('0',np.mean(array_example,0))
#print('1',np.mean(array_example,1))
#print('2',np.mean(array_example,2))

size: 12
Dimension: 3
0 [[0. 1.]
 [4. 5.]]


In [ ]:
import numpy as np
a=np.array([[1,2],[3,4]])
print(a)
print(pow(a,2))

[[1 2]
 [3 4]]
[[ 1  4]
 [ 9 16]]
